version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - solr
    env_file: 
      - ./env/dev.env
    volumes: 
      - .:/github.com/azeezolaniran2016/solr-server
      - ~/Downloads/solr-8.5.1/server/solr:/github.com/azeezolaniran2016/solr-server/solr
    command: 
      realize start
    ports: 
      - 4040:80
  # Todo: Figure how to configure Solr
  solr:
    image: solr:8.5-slim
    ports: 
      - 8983:8983
    volumes: 
      - ./solr_data:/var/solr
     